-- AlterTable
ALTER TABLE `insurancecompany` MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'DRAFT', 'REJECTED') NOT NULL DEFAULT 'ACTIVE';

-- AlterTable
ALTER TABLE `policy` MODIFY `status` ENUM('DRAFT','PENDING','ACCEPTED','REJECTED') NOT NULL DEFAULT 'DRAFT';
